<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>OBSJukeboxSetup</AssemblyName>
    <Authors>babbur</Authors>
    <Company>babbur</Company>
    <Product>OBS Jukebox</Product>
    <Description>Separate GD/Song output for OBS</Description>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>logo.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="logo.png" LogicalName="logo.png" />
    <EmbeddedResource Include="payload.zip" Condition="Exists('payload.zip')" LogicalName="payload.zip" />
  </ItemGroup>
</Project>
